// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("map_id", Name = "map_id")]
public partial class climb
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_id { get; set; }

    [Required]
    [StringLength(1000)]
    public string video { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_x { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_y { get; set; }

    [ForeignKey("map_id")]
    [InverseProperty("climbs")]
    public virtual map map { get; set; }
}