// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("Current_Team_Id", Name = "Current_Team_Id")]
public partial class coach
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string coach_Name { get; set; }

    [Column(TypeName = "int(11)")]
    public int Current_Team_Id { get; set; }

    [ForeignKey("Current_Team_Id")]
    [InverseProperty("coaches")]
    public virtual Team Current_Team { get; set; }

    [InverseProperty("coach")]
    public virtual ICollection<tour_coach> tour_coaches { get; set; } = new List<tour_coach>();
}