// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

public partial class did_you_know_vid
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string name { get; set; }

    [Required]
    [StringLength(200)]
    public string img { get; set; }

    [Required]
    [StringLength(200)]
    public string video_link { get; set; }
}