// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("map_id", Name = "pois_ibfk_1")]
[Index("season_id", Name = "pois_ibfk_2")]
[MySqlCollation("utf8mb4_unicode_ci")]
public partial class Landing_poi
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string poi_name { get; set; }

    [Column(TypeName = "int(20)")]
    public int map_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int season_id { get; set; }

    [Required]
    [StringLength(200)]
    public string img { get; set; }

    [Required]
    [StringLength(200)]
    public string over_loot_img { get; set; }

    [Required]
    [StringLength(200)]
    public string loot_path_img { get; set; }

    [Required]
    [StringLength(200)]
    public string ext_loot_path_img { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_hover_x { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_hover_y { get; set; }

    [Required]
    [StringLength(200)]
    public string hover_img { get; set; }

    [InverseProperty("poi")]
    public virtual ICollection<loot_detail_info> loot_detail_infos { get; set; } = new List<loot_detail_info>();

    [InverseProperty("poi")]
    public virtual ICollection<loot_info> loot_infos { get; set; } = new List<loot_info>();

    [ForeignKey("map_id")]
    [InverseProperty("Landing_pois")]
    public virtual map map { get; set; }

    [ForeignKey("season_id")]
    [InverseProperty("Landing_pois")]
    public virtual season season { get; set; }

    [InverseProperty("landing_poi")]
    public virtual ICollection<team_rotation> team_rotations { get; set; } = new List<team_rotation>();
}