// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[MySqlCollation("utf8mb4_unicode_ci")]
public partial class legend
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string legend_name { get; set; }

    [StringLength(10)]
    public string legend_name_shortcut { get; set; }

    [StringLength(200)]
    public string image { get; set; }

    [InverseProperty("Legend_1")]
    public virtual ICollection<tour_detail_stat> tour_detail_statLegend_1s { get; set; } = new List<tour_detail_stat>();

    [InverseProperty("Legend_2")]
    public virtual ICollection<tour_detail_stat> tour_detail_statLegend_2s { get; set; } = new List<tour_detail_stat>();

    [InverseProperty("Legend_3")]
    public virtual ICollection<tour_detail_stat> tour_detail_statLegend_3s { get; set; } = new List<tour_detail_stat>();

    [InverseProperty("legend")]
    public virtual ICollection<tour_inv_leg> tour_inv_legs { get; set; } = new List<tour_inv_leg>();

    [InverseProperty("legend1")]
    public virtual ICollection<tour_map_stat> tour_map_statlegend1s { get; set; } = new List<tour_map_stat>();

    [InverseProperty("legend2")]
    public virtual ICollection<tour_map_stat> tour_map_statlegend2s { get; set; } = new List<tour_map_stat>();

    [InverseProperty("legend3")]
    public virtual ICollection<tour_map_stat> tour_map_statlegend3s { get; set; } = new List<tour_map_stat>();

    [InverseProperty("Legend_1")]
    public virtual ICollection<tour_stat> tour_statLegend_1s { get; set; } = new List<tour_stat>();

    [InverseProperty("Legend_2")]
    public virtual ICollection<tour_stat> tour_statLegend_2s { get; set; } = new List<tour_stat>();

    [InverseProperty("Legend_3")]
    public virtual ICollection<tour_stat> tour_statLegend_3s { get; set; } = new List<tour_stat>();

    [InverseProperty("legend_Id_1Navigation")]
    public virtual ICollection<tour_team_metum> tour_team_metumlegend_Id_1Navigations { get; set; } = new List<tour_team_metum>();

    [InverseProperty("legend_Id_2Navigation")]
    public virtual ICollection<tour_team_metum> tour_team_metumlegend_Id_2Navigations { get; set; } = new List<tour_team_metum>();

    [InverseProperty("legend_Id_3Navigation")]
    public virtual ICollection<tour_team_metum> tour_team_metumlegend_Id_3Navigations { get; set; } = new List<tour_team_metum>();

    [InverseProperty("legend")]
    public virtual ICollection<tour_team_stats_map_inv_metum> tour_team_stats_map_inv_meta { get; set; } = new List<tour_team_stats_map_inv_metum>();

    [InverseProperty("legend_Id_1Navigation")]
    public virtual ICollection<tour_team_stats_map_metum> tour_team_stats_map_metumlegend_Id_1Navigations { get; set; } = new List<tour_team_stats_map_metum>();

    [InverseProperty("legend_Id_2Navigation")]
    public virtual ICollection<tour_team_stats_map_metum> tour_team_stats_map_metumlegend_Id_2Navigations { get; set; } = new List<tour_team_stats_map_metum>();

    [InverseProperty("legend_Id_3Navigation")]
    public virtual ICollection<tour_team_stats_map_metum> tour_team_stats_map_metumlegend_Id_3Navigations { get; set; } = new List<tour_team_stats_map_metum>();

    [InverseProperty("legend")]
    public virtual ICollection<tour_team_stats_overall_inv_metum> tour_team_stats_overall_inv_meta { get; set; } = new List<tour_team_stats_overall_inv_metum>();

    [InverseProperty("legend_Id_1Navigation")]
    public virtual ICollection<tour_team_stats_overall_metum> tour_team_stats_overall_metumlegend_Id_1Navigations { get; set; } = new List<tour_team_stats_overall_metum>();

    [InverseProperty("legend_Id_2Navigation")]
    public virtual ICollection<tour_team_stats_overall_metum> tour_team_stats_overall_metumlegend_Id_2Navigations { get; set; } = new List<tour_team_stats_overall_metum>();

    [InverseProperty("legend_Id_3Navigation")]
    public virtual ICollection<tour_team_stats_overall_metum> tour_team_stats_overall_metumlegend_Id_3Navigations { get; set; } = new List<tour_team_stats_overall_metum>();
}