// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("loot_detail_info")]
[Index("map_id", Name = "map_id")]
[Index("poi_id", Name = "poi_id")]
public partial class loot_detail_info
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int poi_id { get; set; }

    [Precision(6, 3)]
    public decimal cell { get; set; }

    [Precision(6, 3)]
    public decimal syringe { get; set; }

    [Precision(6, 3)]
    public decimal bat { get; set; }

    [Precision(6, 3)]
    public decimal medkit { get; set; }

    [Precision(6, 3)]
    public decimal phoenix { get; set; }

    [Precision(6, 3)]
    public decimal ult_acc { get; set; }

    [Precision(6, 3)]
    public decimal leg_back { get; set; }

    [Precision(6, 3)]
    public decimal epic_back { get; set; }

    [Column("2x")]
    [Precision(6, 3)]
    public decimal _2x { get; set; }

    [Column("3x")]
    [Precision(6, 3)]
    public decimal _3x { get; set; }

    [Column("2x-4x")]
    [Precision(6, 3)]
    public decimal _2x_4x { get; set; }

    [Precision(6, 3)]
    public decimal EVAC { get; set; }

    [ForeignKey("map_id")]
    [InverseProperty("loot_detail_infos")]
    public virtual map map { get; set; }

    [ForeignKey("poi_id")]
    [InverseProperty("loot_detail_infos")]
    public virtual Landing_poi poi { get; set; }
}