// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("loot_info")]
[Index("map_id", Name = "map_id")]
[Index("poi_id", Name = "poi_id")]
public partial class loot_info
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int poi_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int total_loots { get; set; }

    [Column(TypeName = "int(11)")]
    public int weapon_ref { get; set; }

    [Column(TypeName = "int(11)")]
    public int lootbins { get; set; }

    [Column(TypeName = "int(11)")]
    public int next_zone_beacons { get; set; }

    [Column(TypeName = "int(11)")]
    public int survey_beacons { get; set; }

    [Column(TypeName = "int(11)")]
    public int crafts { get; set; }

    [Column(TypeName = "int(11)")]
    public int respawn_beacons { get; set; }

    [Column(TypeName = "int(11)")]
    public int weapon_racks { get; set; }

    [ForeignKey("map_id")]
    [InverseProperty("loot_infos")]
    public virtual map map { get; set; }

    [ForeignKey("poi_id")]
    [InverseProperty("loot_infos")]
    public virtual Landing_poi poi { get; set; }
}