// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[MySqlCollation("utf8mb4_unicode_ci")]
public partial class map
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string map_name { get; set; }

    [Required]
    [StringLength(20)]
    public string map_name_shortcut { get; set; }

    [Required]
    [StringLength(200)]
    public string img { get; set; }

    [Required]
    [StringLength(200)]
    public string logo_img { get; set; }

    [InverseProperty("map")]
    public virtual ICollection<Landing_poi> Landing_pois { get; set; } = new List<Landing_poi>();

    [InverseProperty("map")]
    public virtual ICollection<alter_void> alter_voids { get; set; } = new List<alter_void>();

    [InverseProperty("map")]
    public virtual ICollection<climb> climbs { get; set; } = new List<climb>();

    [InverseProperty("map")]
    public virtual ICollection<evac> evacs { get; set; } = new List<evac>();

    [InverseProperty("map")]
    public virtual ICollection<jump_tower> jump_towers { get; set; } = new List<jump_tower>();

    [InverseProperty("map")]
    public virtual ICollection<loot_detail_info> loot_detail_infos { get; set; } = new List<loot_detail_info>();

    [InverseProperty("map")]
    public virtual ICollection<loot_info> loot_infos { get; set; } = new List<loot_info>();

    [InverseProperty("map")]
    public virtual ICollection<map_loot> map_loots { get; set; } = new List<map_loot>();

    [InverseProperty("map")]
    public virtual ICollection<map_spawn_rate> map_spawn_rates { get; set; } = new List<map_spawn_rate>();

    [InverseProperty("map")]
    public virtual ICollection<playable_spot> playable_spots { get; set; } = new List<playable_spot>();

    [InverseProperty("map")]
    public virtual ICollection<poi> pois { get; set; } = new List<poi>();

    [InverseProperty("map")]
    public virtual ICollection<rat_spot> rat_spots { get; set; } = new List<rat_spot>();

    [InverseProperty("map")]
    public virtual ICollection<team_rotation> team_rotations { get; set; } = new List<team_rotation>();

    [InverseProperty("map")]
    public virtual ICollection<tour_detail_stat> tour_detail_stats { get; set; } = new List<tour_detail_stat>();

    [InverseProperty("map")]
    public virtual ICollection<tour_map_stat> tour_map_stats { get; set; } = new List<tour_map_stat>();

    [InverseProperty("map")]
    public virtual ICollection<tour_team_map_stat> tour_team_map_stats { get; set; } = new List<tour_team_map_stat>();

    [InverseProperty("map")]
    public virtual ICollection<tour_team_stats_map_inv_metum> tour_team_stats_map_inv_meta { get; set; } = new List<tour_team_stats_map_inv_metum>();

    [InverseProperty("map")]
    public virtual ICollection<tour_team_stats_map_metum> tour_team_stats_map_meta { get; set; } = new List<tour_team_stats_map_metum>();

    [InverseProperty("map1")]
    public virtual ICollection<tournament> tournamentmap1s { get; set; } = new List<tournament>();

    [InverseProperty("map2")]
    public virtual ICollection<tournament> tournamentmap2s { get; set; } = new List<tournament>();

    [InverseProperty("map")]
    public virtual ICollection<uav_range> uav_ranges { get; set; } = new List<uav_range>();
}