// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("map_loot")]
[Index("map_id", Name = "map_id")]
public partial class map_loot
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_id { get; set; }

    [Required]
    [StringLength(200)]
    public string loot_qty_map { get; set; }

    [Required]
    [StringLength(200)]
    public string cargo_bot { get; set; }

    [ForeignKey("map_id")]
    [InverseProperty("map_loots")]
    public virtual map map { get; set; }
}