// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("map_spawn_rate")]
[Index("map_id", Name = "map_id")]
public partial class map_spawn_rate
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_id { get; set; }

    [Required]
    [StringLength(200)]
    public string uav_spawn { get; set; }

    [Required]
    [StringLength(200)]
    public string console_spawn { get; set; }

    [Required]
    [StringLength(200)]
    public string hotzone_spawn { get; set; }

    [Required]
    [StringLength(200)]
    public string ship_spawn { get; set; }

    [Required]
    [StringLength(200)]
    public string assault_bin_spawn_25px { get; set; }

    [Required]
    [StringLength(200)]
    public string assault_bin_spawn_areas { get; set; }

    [Required]
    [StringLength(200)]
    public string assault_bin_spawn_all { get; set; }

    [Required]
    [StringLength(200)]
    public string evo_harvester_spawn_25px { get; set; }

    [Required]
    [StringLength(200)]
    public string evo_harvester_spawn_areas { get; set; }

    [Required]
    [StringLength(200)]
    public string evo_harvester_spawn_all { get; set; }

    [ForeignKey("map_id")]
    [InverseProperty("map_spawn_rates")]
    public virtual map map { get; set; }
}