// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("menu_main")]
[Index("view_id", Name = "view_id")]
public partial class menu_main
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string text { get; set; }

    [Column(TypeName = "int(11)")]
    public int? view_id { get; set; }

    [InverseProperty("main_menu")]
    public virtual ICollection<menu_sub> menu_subs { get; set; } = new List<menu_sub>();

    [ForeignKey("view_id")]
    [InverseProperty("menu_mains")]
    public virtual view view { get; set; }
}