// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("menu_sub")]
[Index("main_menu_id", Name = "main_menu_id")]
[Index("view_id", Name = "view_id")]
public partial class menu_sub
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string text { get; set; }

    [Column(TypeName = "int(11)")]
    public int main_menu_id { get; set; }

    [Required]
    [StringLength(200)]
    public string controller_link { get; set; }

    [Required]
    [StringLength(200)]
    public string action_link { get; set; }

    [StringLength(200)]
    public string att { get; set; }

    [Column(TypeName = "int(11)")]
    public int? view_id { get; set; }

    [ForeignKey("main_menu_id")]
    [InverseProperty("menu_subs")]
    public virtual menu_main main_menu { get; set; }

    [ForeignKey("view_id")]
    [InverseProperty("menu_subs")]
    public virtual view view { get; set; }
}