// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("Current_Team_Id", Name = "Current_Team_Id")]
public partial class Player
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string Player_Name { get; set; }

    [Column(TypeName = "int(11)")]
    public int Current_Team_Id { get; set; }

    [ForeignKey("Current_Team_Id")]
    [InverseProperty("Players")]
    public virtual Team Current_Team { get; set; }

    [InverseProperty("player")]
    public virtual ICollection<tour_player> tour_players { get; set; } = new List<tour_player>();
}