// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[MySqlCollation("utf8mb4_unicode_ci")]
public partial class region
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string region_name { get; set; }

    [Required]
    [StringLength(20)]
    public string region_name_shortcut { get; set; }

    [InverseProperty("region")]
    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();
}