// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[MySqlCollation("utf8mb4_unicode_ci")]
public partial class season
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int season_number { get; set; }

    [StringLength(200)]
    public string season_name { get; set; }

    [InverseProperty("season")]
    public virtual ICollection<Landing_poi> Landing_pois { get; set; } = new List<Landing_poi>();

    [InverseProperty("season")]
    public virtual ICollection<poi> pois { get; set; } = new List<poi>();
}