// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("region_id", Name = "region_id")]
[MySqlCollation("utf8mb4_unicode_ci")]
public partial class Team
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string team_name { get; set; }

    [Required]
    [StringLength(20)]
    public string team_name_shortcut { get; set; }

    [Column(TypeName = "int(11)")]
    public int region_id { get; set; }

    [Required]
    [StringLength(200)]
    public string team_img { get; set; }

    [InverseProperty("Current_Team")]
    public virtual ICollection<Player> Players { get; set; } = new List<Player>();

    [InverseProperty("Current_Team")]
    public virtual ICollection<coach> coaches { get; set; } = new List<coach>();

    [ForeignKey("region_id")]
    [InverseProperty("Teams")]
    public virtual region region { get; set; }

    [InverseProperty("team")]
    public virtual ICollection<team_rotation> team_rotations { get; set; } = new List<team_rotation>();

    [InverseProperty("team")]
    public virtual ICollection<tour_coach> tour_coaches { get; set; } = new List<tour_coach>();

    [InverseProperty("team")]
    public virtual ICollection<tour_detail_stat> tour_detail_stats { get; set; } = new List<tour_detail_stat>();

    [InverseProperty("team")]
    public virtual ICollection<tour_map_stat> tour_map_stats { get; set; } = new List<tour_map_stat>();

    [InverseProperty("team")]
    public virtual ICollection<tour_player> tour_players { get; set; } = new List<tour_player>();

    [InverseProperty("team")]
    public virtual ICollection<tour_stat> tour_stats { get; set; } = new List<tour_stat>();

    [InverseProperty("team")]
    public virtual ICollection<tour_team_map_stat> tour_team_map_stats { get; set; } = new List<tour_team_map_stat>();

    [InverseProperty("team")]
    public virtual ICollection<tour_team_stat> tour_team_stats { get; set; } = new List<tour_team_stat>();

    [InverseProperty("team")]
    public virtual ICollection<tour_team_stats_map_inv_metum> tour_team_stats_map_inv_meta { get; set; } = new List<tour_team_stats_map_inv_metum>();

    [InverseProperty("team")]
    public virtual ICollection<tour_team_stats_map_metum> tour_team_stats_map_meta { get; set; } = new List<tour_team_stats_map_metum>();

    [InverseProperty("team")]
    public virtual ICollection<tour_team_stats_overall_inv_metum> tour_team_stats_overall_inv_meta { get; set; } = new List<tour_team_stats_overall_inv_metum>();

    [InverseProperty("team")]
    public virtual ICollection<tour_team_stats_overall_metum> tour_team_stats_overall_meta { get; set; } = new List<tour_team_stats_overall_metum>();

    [InverseProperty("winner_team")]
    public virtual ICollection<tournament> tournaments { get; set; } = new List<tournament>();
}