// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("team_rotation")]
[Index("endzone_poi_id", Name = "endzone_poi_id")]
[Index("landing_poi_id", Name = "landing_poi_id")]
[Index("map_id", Name = "map_id")]
[Index("team_id", Name = "team_id")]
[Index("tour_id", Name = "tour_id")]
public partial class team_rotation
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int tour_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int team_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int landing_poi_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int endzone_poi_id { get; set; }

    [Required]
    [StringLength(200)]
    public string img { get; set; }

    [ForeignKey("endzone_poi_id")]
    [InverseProperty("team_rotations")]
    public virtual poi endzone_poi { get; set; }

    [ForeignKey("landing_poi_id")]
    [InverseProperty("team_rotations")]
    public virtual Landing_poi landing_poi { get; set; }

    [ForeignKey("map_id")]
    [InverseProperty("team_rotations")]
    public virtual map map { get; set; }

    [ForeignKey("team_id")]
    [InverseProperty("team_rotations")]
    public virtual Team team { get; set; }

    [ForeignKey("tour_id")]
    [InverseProperty("team_rotations")]
    public virtual tournament tour { get; set; }
}