// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("Legend_1_id", Name = "Legend_1_id")]
[Index("Legend_2_id", Name = "Legend_2_id")]
[Index("Legend_3_id", Name = "Legend_3_id")]
[Index("team_id", Name = "team_id")]
[Index("tour_id", Name = "tour_id")]
[MySqlCollation("utf8mb4_unicode_ci")]
public partial class tour_stat
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int tour_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int team_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int tour_stand { get; set; }

    [Precision(6, 1)]
    public decimal av_po_per_game { get; set; }

    [Precision(6, 1)]
    public decimal av_kills_per_game { get; set; }

    [Precision(6, 1)]
    public decimal av_place_per_game { get; set; }

    [Precision(6, 2)]
    public decimal win_rate { get; set; }

    [Precision(6, 2)]
    public decimal top_5_rate { get; set; }

    [Precision(6, 2)]
    public decimal top_10_rate { get; set; }

    [Column(TypeName = "int(11)")]
    public int no_of_games { get; set; }

    [Column(TypeName = "int(11)")]
    public int Legend_1_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int Legend_2_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int Legend_3_id { get; set; }

    [ForeignKey("Legend_1_id")]
    [InverseProperty("tour_statLegend_1s")]
    public virtual legend Legend_1 { get; set; }

    [ForeignKey("Legend_2_id")]
    [InverseProperty("tour_statLegend_2s")]
    public virtual legend Legend_2 { get; set; }

    [ForeignKey("Legend_3_id")]
    [InverseProperty("tour_statLegend_3s")]
    public virtual legend Legend_3 { get; set; }

    [ForeignKey("team_id")]
    [InverseProperty("tour_stats")]
    public virtual Team team { get; set; }

    [ForeignKey("tour_id")]
    [InverseProperty("tour_stats")]
    public virtual tournament tour { get; set; }
}