// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("coach_Id", Name = "player_Id")]
[Index("team_id", Name = "team_id")]
[Index("tour_id", Name = "tour_id")]
public partial class tour_coach
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int coach_Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int team_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int tour_id { get; set; }

    [ForeignKey("coach_Id")]
    [InverseProperty("tour_coaches")]
    public virtual coach coach { get; set; }

    [ForeignKey("team_id")]
    [InverseProperty("tour_coaches")]
    public virtual Team team { get; set; }

    [ForeignKey("tour_id")]
    [InverseProperty("tour_coaches")]
    public virtual tournament tour { get; set; }
}