// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("tour_inv_leg")]
[Index("legend_id", Name = "legend")]
[Index("tour_id", Name = "tour_id")]
[MySqlCollation("utf8mb4_unicode_ci")]
public partial class tour_inv_leg
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int tour_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int legend_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int pick_rate { get; set; }

    [Column(TypeName = "int(11)")]
    public int total { get; set; }

    [ForeignKey("legend_id")]
    [InverseProperty("tour_inv_legs")]
    public virtual legend legend { get; set; }

    [ForeignKey("tour_id")]
    [InverseProperty("tour_inv_legs")]
    public virtual tournament tour { get; set; }
}