// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("legend_Id", Name = "legend_Id_1")]
[Index("map_id", Name = "map_id")]
[Index("team_id", Name = "team_id")]
[Index("tour_id", Name = "tour_id")]
public partial class tour_team_stats_map_inv_metum
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int tour_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int team_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int legend_Id { get; set; }

    [Precision(6, 2)]
    public decimal pick_rate { get; set; }

    [Column(TypeName = "int(11)")]
    public int Total { get; set; }

    [ForeignKey("legend_Id")]
    [InverseProperty("tour_team_stats_map_inv_meta")]
    public virtual legend legend { get; set; }

    [ForeignKey("map_id")]
    [InverseProperty("tour_team_stats_map_inv_meta")]
    public virtual map map { get; set; }

    [ForeignKey("team_id")]
    [InverseProperty("tour_team_stats_map_inv_meta")]
    public virtual Team team { get; set; }

    [ForeignKey("tour_id")]
    [InverseProperty("tour_team_stats_map_inv_meta")]
    public virtual tournament tour { get; set; }
}