// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("player_Id", Name = "player_Id")]
[Index("team_id", Name = "team_id")]
[Index("tour_id", Name = "tour_id")]
public partial class tour_player
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int player_Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int team_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int tour_id { get; set; }

    [ForeignKey("player_Id")]
    [InverseProperty("tour_players")]
    public virtual Player player { get; set; }

    [ForeignKey("team_id")]
    [InverseProperty("tour_players")]
    public virtual Team team { get; set; }

    [ForeignKey("tour_id")]
    [InverseProperty("tour_players")]
    public virtual tournament tour { get; set; }
}