// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("map1_id", Name = "map1_id")]
[Index("map2_id", Name = "map2_id")]
[Index("winner_team_id", Name = "winner_team_id")]
[MySqlCollation("utf8mb4_unicode_ci")]
public partial class tournament
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string tour_name { get; set; }

    [Required]
    [StringLength(20)]
    public string tour_name_shortcut { get; set; }

    [Column(TypeName = "int(4)")]
    public int year { get; set; }

    [Column(TypeName = "int(11)")]
    public int? winner_team_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map1_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map2_id { get; set; }

    [ForeignKey("map1_id")]
    [InverseProperty("tournamentmap1s")]
    public virtual map map1 { get; set; }

    [ForeignKey("map2_id")]
    [InverseProperty("tournamentmap2s")]
    public virtual map map2 { get; set; }

    [InverseProperty("tour")]
    public virtual ICollection<team_rotation> team_rotations { get; set; } = new List<team_rotation>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_coach> tour_coaches { get; set; } = new List<tour_coach>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_detail_stat> tour_detail_stats { get; set; } = new List<tour_detail_stat>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_inv_leg> tour_inv_legs { get; set; } = new List<tour_inv_leg>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_map_stat> tour_map_stats { get; set; } = new List<tour_map_stat>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_player> tour_players { get; set; } = new List<tour_player>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_stat> tour_stats { get; set; } = new List<tour_stat>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_team_map_stat> tour_team_map_stats { get; set; } = new List<tour_team_map_stat>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_team_metum> tour_team_meta { get; set; } = new List<tour_team_metum>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_team_stat> tour_team_stats { get; set; } = new List<tour_team_stat>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_team_stats_map_inv_metum> tour_team_stats_map_inv_meta { get; set; } = new List<tour_team_stats_map_inv_metum>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_team_stats_map_metum> tour_team_stats_map_meta { get; set; } = new List<tour_team_stats_map_metum>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_team_stats_overall_inv_metum> tour_team_stats_overall_inv_meta { get; set; } = new List<tour_team_stats_overall_inv_metum>();

    [InverseProperty("tour")]
    public virtual ICollection<tour_team_stats_overall_metum> tour_team_stats_overall_meta { get; set; } = new List<tour_team_stats_overall_metum>();

    [ForeignKey("winner_team_id")]
    [InverseProperty("tournaments")]
    public virtual Team winner_team { get; set; }
}