// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("tour_map_stat")]
[Index("legend1_id", Name = "legend1_id")]
[Index("legend2_id", Name = "legend2_id")]
[Index("legend3_id", Name = "legend3_id")]
[Index("map_id", Name = "map_id")]
[Index("team_id", Name = "team_id")]
[Index("tour_id", Name = "tour_id")]
public partial class tour_map_stat
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int tour_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int map_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int team_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int stand { get; set; }

    [Precision(6, 1)]
    public decimal av_po { get; set; }

    [Precision(6, 1)]
    public decimal av_ki { get; set; }

    [Precision(6, 1)]
    public decimal av_pl { get; set; }

    [Precision(6, 2)]
    public decimal win_rate { get; set; }

    [Precision(6, 2)]
    public decimal top_5_rate { get; set; }

    [Precision(6, 2)]
    public decimal top_10_rate { get; set; }

    [Column(TypeName = "int(11)")]
    public int no_games { get; set; }

    [Column(TypeName = "int(11)")]
    public int legend1_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int legend2_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int legend3_id { get; set; }

    [ForeignKey("legend1_id")]
    [InverseProperty("tour_map_statlegend1s")]
    public virtual legend legend1 { get; set; }

    [ForeignKey("legend2_id")]
    [InverseProperty("tour_map_statlegend2s")]
    public virtual legend legend2 { get; set; }

    [ForeignKey("legend3_id")]
    [InverseProperty("tour_map_statlegend3s")]
    public virtual legend legend3 { get; set; }

    [ForeignKey("map_id")]
    [InverseProperty("tour_map_stats")]
    public virtual map map { get; set; }

    [ForeignKey("team_id")]
    [InverseProperty("tour_map_stats")]
    public virtual Team team { get; set; }

    [ForeignKey("tour_id")]
    [InverseProperty("tour_map_stats")]
    public virtual tournament tour { get; set; }
}