// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Index("legend_Id_1", Name = "legend_Id_1")]
[Index("legend_Id_2", Name = "legend_Id_2")]
[Index("legend_Id_3", Name = "legend_Id_3")]
[Index("tour_id", Name = "tour_id")]
[MySqlCollation("utf8mb4_unicode_ci")]
public partial class tour_team_metum
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int tour_id { get; set; }

    [Column(TypeName = "int(11)")]
    public int legend_Id_1 { get; set; }

    [Column(TypeName = "int(11)")]
    public int legend_Id_2 { get; set; }

    [Column(TypeName = "int(11)")]
    public int legend_Id_3 { get; set; }

    [Precision(6, 1)]
    public decimal pick_rate { get; set; }

    [Column(TypeName = "int(11)")]
    public int total { get; set; }

    [ForeignKey("legend_Id_1")]
    [InverseProperty("tour_team_metumlegend_Id_1Navigations")]
    public virtual legend legend_Id_1Navigation { get; set; }

    [ForeignKey("legend_Id_2")]
    [InverseProperty("tour_team_metumlegend_Id_2Navigations")]
    public virtual legend legend_Id_2Navigation { get; set; }

    [ForeignKey("legend_Id_3")]
    [InverseProperty("tour_team_metumlegend_Id_3Navigations")]
    public virtual legend legend_Id_3Navigation { get; set; }

    [ForeignKey("tour_id")]
    [InverseProperty("tour_team_meta")]
    public virtual tournament tour { get; set; }
}