// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

[Table("viewsaccess")]
[Index("view_id", Name = "view_id")]
[Index("role_name", Name = "viewsaccess_ibfk_2")]
public partial class viewsaccess
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Column(TypeName = "int(11)")]
    public int view_id { get; set; }

    [Required]
    public string role_name { get; set; }

    [ForeignKey("view_id")]
    [InverseProperty("viewsaccesses")]
    public virtual view view { get; set; }
}