// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Privacy_Web_App.DataContext;

public partial class view
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string viewname { get; set; }

    [Required]
    [StringLength(200)]
    public string section { get; set; }

    [Required]
    [StringLength(200)]
    public string action_name { get; set; }

    [Required]
    [StringLength(200)]
    public string controller { get; set; }

    [InverseProperty("view")]
    public virtual ICollection<menu_main> menu_mains { get; set; } = new List<menu_main>();

    [InverseProperty("view")]
    public virtual ICollection<menu_sub> menu_subs { get; set; } = new List<menu_sub>();

    [InverseProperty("view")]
    public virtual ICollection<viewsaccess> viewsaccesses { get; set; } = new List<viewsaccess>();
}