// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using Privacy_Web_App.DataContext;
using Privacy_Web_App.Models;

public class TeamModel
{
    public int Id { get; set; }

    
    public string team_name { get; set; }

   
    public string team_name_shortcut { get; set; }

   
    public int region_id { get; set; }

    public string region_Name { get; set; }

    public string team_img { get; set; }

}
public class TeamsListModel 
{
    public IEnumerable<PlayerModel> players { get; set; }
    public IEnumerable<TeamModel> teams { get; set; }
    public IEnumerable<CoacheModel> coaches { get; set; }
    public IEnumerable<RegionModel> regions { get; set; }




}


public class TeamInfoModel { 
    public int Id { get; set; }


    public string team_name { get; set; }


    public string team_name_shortcut { get; set; }


    public int region_id { get; set; }

    public string region_Name { get; set; }

    public string team_img { get; set; }


    public IEnumerable<PlayerModel> players { get; set; }

    public IEnumerable<CoacheModel> coaches { get; set; }

    public IEnumerable<TournamentStatsModel> tours { get; set; }

    
}
public class TeamStatViewModel
{
    public int Id { get; set; }
    public string team_name { get; set; }
    public string team_name_shortcut { get; set; }
    public int region_id { get; set; }
    public string region_Name { get; set; }
    public string team_img { get; set; }
    public IEnumerable<TourPlayerModel> players { get; set; }
    public IEnumerable<TourCoachModel> coaches { get; set; }
    public IEnumerable<TournamentStatsModel> tourstats { get; set; }

    public IEnumerable<TourTeamStatsModel> tourTeamStats { get; set; }


    public IEnumerable<TourTeamMapStatsModel> mapStats1 { get; set; }

    public IEnumerable<TourTeamMapStatsModel> mapStats2 { get; set; }

    public IEnumerable<TourTeamOverMetaModel> overMeta { get; set; }

    public IEnumerable<TourTeamMapMetaModel> overMapMeta1 { get; set; }

    public IEnumerable<TourTeamMapMetaModel> overMapMeta2 { get; set; }


    public IEnumerable<TourTeamOverInvMetaModel> overInvMeta { get; set; }

    public IEnumerable<TourTeamMapInvMetaModel> overMapInvMeta1 { get; set; }

    public IEnumerable<TourTeamMapInvMetaModel> overMapInvMeta2 { get; set; }




}